name: py36
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.8
    - numpy==1.19.2
    - matplotlib==3.3.4
    - jupyter==1.0.0
    - scikit-learn==0.24.1
    - scipy==1.6.2
    - seaborn==0.11.1
    - pandas==1.2.3
